# Generated by Django 3.2.5 on 2022-08-03 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitaplar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kitap',
            old_name='yaratilme_tarihi',
            new_name='yaratilma_tarihi',
        ),
        migrations.RenameField(
            model_name='yorum',
            old_name='yaratilme_tarihi',
            new_name='yaratilma_tarihi',
        ),
    ]
