# Generated by Django 3.2.5 on 2022-08-06 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kitaplar', '0002_auto_20220803_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yorum',
            name='yorum_sahibi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kullanici_yorumlari', to=settings.AUTH_USER_MODEL),
        ),
    ]
